-- Early access conversion funnel and signup responses.
-- Safe to run more than once.

create table if not exists public.early_access_signups (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  email text not null,
  gender text,
  age_range text,
  work_role text,
  primary_use_case text,
  consent_marketing boolean not null default false,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  landing_page text,
  referrer text,
  user_agent text,
  timezone text,
  submitted_at timestamptz not null default now()
);

create unique index if not exists early_access_signups_email_unique
  on public.early_access_signups (lower(email));
create index if not exists early_access_signups_submitted_at_idx
  on public.early_access_signups (submitted_at desc);

create table if not exists public.early_access_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  event_name text not null,
  step_name text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists early_access_events_created_at_idx
  on public.early_access_events (created_at desc);
create index if not exists early_access_events_session_idx
  on public.early_access_events (session_id);

alter table public.early_access_signups enable row level security;
alter table public.early_access_events enable row level security;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

revoke all on function public.current_user_is_admin() from public;
grant execute on function public.current_user_is_admin() to authenticated;

drop policy if exists "public can submit early access" on public.early_access_signups;
create policy "public can submit early access"
  on public.early_access_signups for insert to anon, authenticated
  with check (
    email is not null
    and consent_marketing = true
    and gender in ('Male', 'Female', 'Non-binary', 'Prefer not to say')
    and age_range in ('18–24', '25–34', '35–44', '45–54', '55+', 'Prefer not to say')
  );

drop policy if exists "admins can read early access" on public.early_access_signups;
create policy "admins can read early access"
  on public.early_access_signups for select to authenticated
  using (public.current_user_is_admin());

drop policy if exists "public can record early access events" on public.early_access_events;
create policy "public can record early access events"
  on public.early_access_events for insert to anon, authenticated
  with check (
    event_name in ('signup_opened', 'signup_step_viewed', 'signup_answered', 'signup_completed')
  );

drop policy if exists "admins can read early access events" on public.early_access_events;
create policy "admins can read early access events"
  on public.early_access_events for select to authenticated
  using (public.current_user_is_admin());

grant insert on public.early_access_signups to anon, authenticated;
grant insert on public.early_access_events to anon, authenticated;
grant select on public.early_access_signups to authenticated;
grant select on public.early_access_events to authenticated;
grant usage, select on sequence public.early_access_events_id_seq to anon, authenticated;

